### ISSUE TITLE
Unresolved reference in multiplatform project

### ISSUE THREAD

**Issue by harry248** [skydoves/compose-stable-marker#1]
First of all, thank you for this library! Unfortunately, I can't get it to work properly yet. Maybe I don't understand it correctly but I tried to use the library in a KMM project. I added the dependency to the commonMain source set (compileOnly) and wanted to annotate our domain models (in the KMM part) with `@Immutable`. However, the annotation is not found (Unresolved Reference). Are there any other configuration steps besides the dependency that I have overlooked?

**Comment by skydoves** [comment]
Hey @harry248, thank you for bringing this issue to my attention. Rest assured, I will carefully consider supporting Kotlin multiplatform in the future releases.

**Comment by skydoves** [comment]
Hey @harry248, the new version 1.0.2 finally supports KMP 🎉 Thanks for reporting this issue and please let me know if you face any issues while importing the new version.
