### ISSUE TITLE
Archive this repository 

### ISSUE THREAD

**Issue by Nek-12** [skydoves/compose-stable-marker#4]
This repository has become obsolete with Compose Compiler 1.5.4, which introduced stability configuration file.

**Comment by skydoves** [comment]
@Nek-12 This library has supported KMP since version 1.0.2. Would you elaborate on your suggestion?

**Comment by Nek-12** [comment]
Yes, I'm sorry, I did not check the chamgelogs. Last time I checked it did not

**Comment by skydoves** [comment]
Well, anyway, thanks for having an interest in this repository. I wish to archive this library one day once the Compose compiler supports stability marking across different independent modules.

**Comment by Nek-12** [comment]
But this issue was created exactly because compose added support for that...
