### ISSUE TITLE
Kmm build warning

### ISSUE THREAD

**Issue by ponvig** [skydoves/compose-stable-marker#8]
Getting these warnings when building KMM Android app:

Dependencies:
com.github.skydoves:compose-stable-marker:1.0.3

Such dependencies are not applicable for Kotlin/Native, consider changing the dependency type to 'implementation' or 'api'.
To disable this warning, set the kotlin.native.ignoreIncorrectDependencies=true project property
A compileOnly dependency is used in the Kotlin/Native target 'iosSimulatorArm64':
Compilation: main

**Comment by skydoves** [comment]
Hey @ponvig, sorry for the delayed response. Would you check out if the 1.0.4 release still faces the same issue?

**Comment by skydoves** [comment]
Duplication of #9
