### ISSUE TITLE
Compile error when building ios app

### ISSUE THREAD

**Issue by panpf** [skydoves/compose-stable-marker#9]
**Please complete the following information:**
- compose-stable-marker: 1.0.3
- jetbrains-compose: 1.6.1
- jetbrains-compose-compiler: 1.5.10
- kotlin: 1.9.23
- gradle: 8.5
 
**Describe the Bug:**
Getting the following compile error while building an ios app
```
> Task :sketch:compileKotlinIosSimulatorArm64 FAILED
error: Could not find "compose-stable-marker:compose-stable-marker" in [/Users/panpf/Workspace/sketch, /Users/panpf/.konan/klib, /Users/panpf/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/common, /Users/panpf/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.23/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors
```

**Comment by skydoves** [comment]
Hey @panpf, sorry for the delayed response. Would you check out if the 1.0.4 release still faces the same issue?

**Comment by panpf** [comment]
I tested version 1.0.4 and it still doesn’t work when compiling ios app.

You can add ios multi-platform to your demo app, then try to compile and run the app on the simulator, and you can reproduce it immediately.

**Comment by panpf** [comment]
This error still exists in version 1.0.5. I found that your demo app only has Android platform. I suggest you add iOS platform to try.

**Comment by skydoves** [comment]
Hey @panpf, are you sure that you use this library in the "pure" KMP module like the example below?

```kotlin
plugins {
  kotlin("multiplatform")
  id("com.android.library")
}
```

You can't use this library on the Compose multiplatform module.

```kotlin
id("org.jetbrains.compose")
```
